#!/usr/bin/env bash

if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]
then
  docker build -t komunumo/komunumo-backend .
  docker login -u $DOCKER_USER -p $DOCKER_PASS
  docker push komunumo/komunumo-backend
  docker logout
fi
